### ISSUE TITLE
5/27 プロト展示に向けて

### ISSUE THREAD

**Issue by kaiba-yoha** [kaiba-yoha/Teruno_Yoichi#4]
## 残りのタスク

- [ ] ネットワーク接続
- [ ] ステージのアセット用意
  - 海？とあと何が必要？
- [ ] ゲームサイクルの作成

**Comment by kaiba-yoha** [comment]
@Shohei-Fujieda @Zinc0816 
作業の方進捗どうでしょうか？忙しくて進捗産むのが難しければ教えてください！
作業が終わったらプルリクエスト作ってもらえると助かります！（プルリクの作り方分からなかったら聞いてください！）

**Comment by Zinc0816** [comment]
作業しようとしているのですが、The name 'OVRInput' does not exist in the current contextというエラーが解決できず、何もできないままです...

**Comment by kaiba-yoha** [comment]
@Zinc0816 
[README](https://github.com/kaiba-yoha/Teruno_Yoichi/blob/main/README.md)のセットアップの項って実行しました？

**Comment by kaiba-yoha** [comment]
@Zinc0816 
リポジトリのデータはOculus Integrationが入ってない状態になっているので入れてなければImportしてください！

**Comment by Zinc0816** [comment]
インポートしている(package manegerのウィンドウではimportではなくremoveになっているので、多分インポートされてるはず...)と思うのですが、エラーが解消できないです...

**Comment by kaiba-yoha** [comment]
@Zinc0816 なるほど…　エラー画面詳しく見せて貰えると助かります！

**Comment by Zinc0816** [comment]
![image](https://user-images.githubusercontent.com/76957000/169831020-8c3d34e2-a215-4c6f-8f79-094e8aef191f.png)
こんな感じです...

**Comment by kaiba-yoha** [comment]
> ![image](https://user-images.githubusercontent.com/76957000/169831020-8c3d34e2-a215-4c6f-8f79-094e8aef191f.png) こんな感じです...

あ、Oculus Integrationはいってないですね。Oculus XR Pluginとは別モノなのでAssets StoreからImportしてください！

**Comment by Zinc0816** [comment]
了解です！先ほどファイアウォール関係のエラーを解消できたのでインポートして作業に移ります！
